// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lttrylqpsgjdxvysulvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0dHJ5bHFwc2dqZHh2eXN1bHZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NzM3MjAsImV4cCI6MjA2NzE0OTcyMH0.NTrzZcO40Oq0RfRYhjoCsNFwVFVhwv39m9h12C4FgLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});